### ISSUE TITLE
Enable GitHub pages

### ISSUE THREAD

**Issue by larsrh** [isaqb-org/curriculum-blockchain#13]
The `gh-branch` exists, but in the settings, it needs to be selected.

**Comment by programming-wolf** [comment]
It is selected.

**Comment by larsrh** [comment]
Then why am I getting a 404 here? https://isaqb-org.github.io/curriculum-blockchain/ :thinking:

**Comment by programming-wolf** [comment]
Try pushing the release again? :-) (rev1)

**Comment by programming-wolf** [comment]
It seemed to be selected, but I had to select it again. 🤷

**Comment by larsrh** [comment]
Excellent! Case closed :detective:
