### ISSUE TITLE
Update/Fix bibliography

### ISSUE THREAD

**Issue by programming-wolf** [isaqb-org/curriculum-blockchain#16]
As the current bibliography does not work at all, it has to be fixed. You can use the updated version of the template, which explains in detail how to properly use the bibliography and its labels. 

In addition, instead of having a bullet list in each chapter with references to the used sources, a comma separated list is way more beautiful.

**Comment by larsrh** [comment]
![](https://i.imgflip.com/3xhwke.jpg)

**Comment by programming-wolf** [comment]
Fixed it for you
